apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhRzl1Wlhsd2IzUTVPbWRvY0Y5U1lYRkhTRkY0TjI1WGRqWkVUM2RXUVhCTllXWjFabWhyUW5saGJuUXdTRmxDTkhJPSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkiamFnYS1uZXh1cy5sdWtpdC5ydSI6IHt9LAoJCSJqYWdhLm5leHVzLmphZ2EucnQucnUiOiB7fSwKCQkibGttcmR2cy1uZXh1cy5sdWtpdC5ydSI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiLXgtY2xpLWhpbnRzIjogewoJCQkiZW5hYmxlZCI6ICJ0cnVlIgoJCX0KCX0sCgkiZmVhdHVyZXMiOiB7CgkJImhvb2tzIjogInRydWUiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
