apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: cinemaabyss
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/http2-push-preload: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
        return 444;
      }
spec:
  ingressClassName: nginx  # ← Новая обязательная спецификация
  rules:
    - host: cinemaabyss.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monolith
                port:
                  number: 8080
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000
          - path: /api/movies
            pathType: Prefix
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: events-service
                port:
                  number: 8082